spring:
  application:
    name: auth
  datasource:
    url: jdbc:mariadb://localhost:3306/auth_database
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  jwt:
    secret-key: abcdefghijklmnopqrstuvwxyz
    access-token-expiration-Millisecond: 3600000 # 60 * 60 * 1000
